// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-sTntUUpa_UjwSocQQSUwc-YKpxhy4Y',
    appId: '1:320415833993:web:cca7ae34175f0193498b58',
    messagingSenderId: '320415833993',
    projectId: 'safezone-c3baa',
    authDomain: 'safezone-c3baa.firebaseapp.com',
    storageBucket: 'safezone-c3baa.firebasestorage.app',
    measurementId: 'G-73WG433HJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByvOChX75YzGkYhDyNx_4Jk2AyITMBUv8',
    appId: '1:320415833993:android:94cf5ed2642b49ef498b58',
    messagingSenderId: '320415833993',
    projectId: 'safezone-c3baa',
    storageBucket: 'safezone-c3baa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4E5abEnxiZTCSuOgnvJrHgJD7slncFSM',
    appId: '1:320415833993:ios:b22de33db20e5339498b58',
    messagingSenderId: '320415833993',
    projectId: 'safezone-c3baa',
    storageBucket: 'safezone-c3baa.firebasestorage.app',
    iosClientId: '320415833993-hckh7dbkjkauv8njl3nl43j3llb0a2bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4E5abEnxiZTCSuOgnvJrHgJD7slncFSM',
    appId: '1:320415833993:ios:b22de33db20e5339498b58',
    messagingSenderId: '320415833993',
    projectId: 'safezone-c3baa',
    storageBucket: 'safezone-c3baa.firebasestorage.app',
    iosClientId: '320415833993-hckh7dbkjkauv8njl3nl43j3llb0a2bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA18UWE-OjMvZFQBh7rgQI51mgX9q4ie6k',
    appId: '1:100170954165:web:c39f8f8fdb3f1584a1d5fc',
    messagingSenderId: '100170954165',
    projectId: 'odc2025-7cf77',
    authDomain: 'odc2025-7cf77.firebaseapp.com',
    storageBucket: 'odc2025-7cf77.firebasestorage.app',
    measurementId: 'G-X2CDT6REMH',
  );

}